<?php

namespace Tests\Feature\Http\Funnels;

use Tests\TestCase;

/**
 * @see \DDD\Http\Funnels\FunnelSearchController
 */
class FunnelSearchControllerTest extends TestCase
{
    /**
     * @test
     */
    public function search_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->getJson('api/{organization}/funnels-search');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
