<?php

namespace Tests\Feature\Http\Dashboards;

use Tests\TestCase;

/**
 * @see \DDD\Http\Dashboards\DashboardFunnelController
 */
class DashboardFunnelControllerTest extends TestCase
{
    /**
     * @test
     */
    public function attach_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/{organization}/dashboards/{dashboard}/funnels/attach', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function detach_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/{organization}/dashboards/{dashboard}/funnels/detach', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
