<?php

namespace Tests\Feature\Http\Base\Media;

use Tests\TestCase;

/**
 * @see \DDD\Http\Base\Media\MediaDownloadController
 */
class MediaDownloadControllerTest extends TestCase
{
    /**
     * @test
     */
    public function download_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->getJson('api/media/{media}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
