<?php

namespace Tests\Feature\Http\Base\Subscriptions\Subscriptions;

use Tests\TestCase;

/**
 * @see \DDD\Http\Base\Subscriptions\Subscriptions\SubscriptionController
 */
class SubscriptionControllerTest extends TestCase
{
    /**
     * @test
     */
    public function store_validates_with_a_form_request(): void
    {
        $this->assertActionUsesFormRequest(
            \DDD\Http\Base\Subscriptions\Subscriptions\SubscriptionController::class,
            'store',
            \DDD\Domain\Base\Subscriptions\Subscriptions\Requests\SubscriptionStoreRequest::class
        );
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/{organization}/subscriptions/subscriptions', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request(): void
    {
        $this->assertActionUsesFormRequest(
            \DDD\Http\Base\Subscriptions\Subscriptions\SubscriptionController::class,
            'update',
            \DDD\Domain\Base\Subscriptions\Subscriptions\Requests\SubscriptionUpdateRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->patchJson('api/{organization}/subscriptions/subscriptions', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
