<?php

namespace Tests\Feature\Http\Base\Auth;

use Tests\TestCase;

/**
 * @see \DDD\Http\Base\Auth\AuthRegisterWithInvitationController
 */
class AuthRegisterWithInvitationControllerTest extends TestCase
{
    /**
     * @test
     */
    public function __invoke_validates_with_a_form_request(): void
    {
        $this->assertActionUsesFormRequest(
            \DDD\Http\Base\Auth\AuthRegisterWithInvitationController::class,
            '__invoke',
            \DDD\Http\Base\Auth\Requests\AuthRegisterWithInvitationRequest::class
        );
    }

    /**
     * @test
     */
    public function invoke_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/auth/register/invitation/{invitation}', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
