<?php

namespace Tests\Feature\Http\Base\Auth;

use Tests\TestCase;

/**
 * @see \DDD\Http\Base\Auth\AuthLogoutController
 */
class AuthLogoutControllerTest extends TestCase
{
    /**
     * @test
     */
    public function invoke_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/auth/logout', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
