<?php

namespace Tests\Feature\Http\Services\GoogleAnalytics;

use Tests\TestCase;

/**
 * @see \DDD\Http\Services\GoogleAnalytics\GoogleAnalyticsAdminController
 */
class GoogleAnalyticsAdminControllerTest extends TestCase
{
    /**
     * @test
     */
    public function list_accounts_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/ga/accounts', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
